apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUFQVzNTQ0kwbmJYU0NOS1hQaUlvXzh2eGtxWjJxQmFNYTBQdXFqN1FuUWtrc3AwSGMwdGRBcjZvWm5sSGpYMEY3WUZWUVpEWGxOa2VmaTI1
